enum ErrorCodes {
    VALIDATION_FAILED = "VALIDATION_FAILED",
    USER_NOT_FOUND = "USER_NOT_FOUND",
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
    CREDENTIALS_TAKEN = "CREDENTIALS_TAKEN",
    UNAUTHORIZED_ACCESS = "UNAUTHORIZED_ACCESS",
    FORBIDDEN_ACCESS = "FORBIDDEN_ACCESS",
    SECRET_NOT_FOUND = "SECRET_NOT_FOUND",
    OTP_INVALID_OR_EXPIRED = "OTP_INVALID_OR_EXPIRED",
    SECRET_EXPIRED = "SECRET_EXPIRED",
}

export default ErrorCodes