enum ErrorCodes {
    VALIDATION_FAILED = "VALIDATION_FAILED",
    USER_NOT_FOUND = "USER_NOT_FOUND",
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
    CREDENTIALS_TAKEN = "CREDENTIALS_TAKEN",
}

export default ErrorCodes